---
title: "06-Conclusion""
output:
  pdf_document: default
  html_document: default
---


#Conclusion

##Summary

Supervised Classification with a manually labeled training set tends to offer the best accuracy rate as evidenced in this experiment.  The accuracy can further be improved as the machine learns new scenarios and the training set improves.  

The other approaches using unsupervised classification is not seen to be effective in a deduplication process.  

##Next Steps

The solution is current built in R. R, being an in-memory statistical engine, scalability of this solution to massive real-world datasets requires to be validated.  However, R provides mechanisms to connect to many popular open source DBs to handle BigData analytics.  This needs to be explored further.  

The solution can be further validated using different real-life scenarios before implementation.   

##Questions & Answers

###Why do we start from an 100% quality dataset in the first place?
This is to ensure that we have control over the "debasement" process.  This way, we will be able to monitor the accuracy of the dedup engine against the quality of the dataset.

###Is it possible to use R to manage real-world data and deduplication?
R is an in-memory statistical engine and has limitations with large datasets.  However, R can connect with popular BigData databases to manage huge datasets.  This is not a popular approach, though.

###Does accuracy improve with increased Training Data
Accuracy is dependent on the training set for the number of unique scenarios.  In case additional error scenarios creep into the dataset, the training set would need to be enhanced.  However, this experiment uses only a fixed number of training set and has been showing consistent performance.

###Will this solution work for languages other than English?
The phonetic engine employed by this solution is one made for the English language.  The solution can scale up to additional languages based on availability of phonetic engines for the respective languages.  Alternatively, string comparison can be utilized for these fields as well.  The quality of the results would need to be further ascertained.

