--- 
title: |
     | Deduplication
     | A Controlled Experiment employing 
     | Machine Learning
author: "Sreekumar Pillai"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook-pdf
documentclass: report
Font size : 12 pt
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: 
description: "This is an case study on deduplication of customer data using probabilistic or Machine Learning approaches."

---

# Executive Summary {-}
\fontsize{12}{22}
\selectfont

Over the years, many organizations acquire duplicate records in their IT systems: each one in different forms.  The variations could be related to the type of records or to the kind of errors they pertain to; as in the case of very simple phonemic errors or even due to missing information in some of the records.  Customer records are the most frequent culprits in this aspect since they tend to register an alternate account at the first onset of not able to trace any previous registrations.  
  
Consolidating these different records, by pairing up similar records and clearing away duplicate ones is referred to as, Record Linkage.  There are many custom products in the market claiming to achieve this functionality.  At the same time, in a practical sense, these tools still needs improvement from an accuracy standpoint and this analysis is expected to provide additional insight into the problem and solution by going a little into the basics to gain more control over the duplication process and devise solutions with the most recent learnings in the discipline.  
  
This research attempts to solve the problem with simulated data.  The whole approach is documented for the purpose of reproducibility and future enhancement.  This study is more of an exploratory attempt to solve the Record Linkage problem from the Customer Records perspective than a scientific research towards any pre-defined hypothesis.  

While a major challenge is with simulating real-world problems in a generated dataset, a simulated one provides more control over the input and output to the experiment, providing more authenticity to the efficiency of the solution.  

In conclusion, this experiment reports 95% accuracy by following a hybrid approach to deduplication employing clerical and Machine learning techniques.

